### ISSUE TITLE
Validation/Templates: which files to provide with onyo default installation?

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#104]
Currently I am providing with the repository, the installation of onyo, and `onyo init` some templates and validation files.

These are just place holder as a proof of concept and to demonstrate the functionalities, I do not think that they otherwise provide any real value to the user.

We should discuss which template files and which validation rules we want to give with onyo per default with every installation, or if we want to leave it like it is right now and let the user decide/overwrite everything manually.

**Comment by aqw** [comment]
We should ship a simple example. There's two common ways to do this:

1) Install a file at the normal config location, and the config contains most examples, and everything is commented out.
2) Install an example file at the normal location, but named differently (for example `config.yaml.example`.

I don't think we should install any validation rules by default --- unless validation is extended to also handle file name rules. Then those should be handled in a config file (where the user can change them) rather than hardcoded, as they currently are.

**Comment by TobiasKadelka** [comment]
For the templates, I keep the `standard` (which is used by `onyo new` by default) and have a simple `laptop.example` that defines some simple keys.

For `validation.yaml`, I will go with the option of preparing one (based on the examples of the readme), and comment out it's contents.
