### ISSUE TITLE
DOC: better examples for templates and validation

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#105]
Currently I am documenting different use cases for the validation, in a similar manner like the documentation for the template examples, that already exists.

In general, my examples will demonstrate the behaviour of onyo, and how to use the `validation.yaml`, so that the user can keep the different assets all over an onyo repository consistent. However, while I demenstrate different use cases and try to keep the example files as short as possible to explain different functions, I am still using the dummy names for keys `RAM` and `Size`, as short and generic terms. Somebody actually working with hardware and having a clearer idea of what information a user might want to have might want to come up with more "real" key names.

It would also be cool to have a "big example", that combines all different functionalities of the section before (rules for specific type of file `shelf/laptop*`, difference between `shelf/*` and `shelf/**`, pointers, etc).

**Comment by aqw** [comment]
I have a suspicion that this issue was filed back when templates were going to be more complicated, with an inheritance structure. That is no longer the case, and reading the docs, templates seem to be well explained.

Validation does not exist (yet), and thus cannot have examples. Those will come when it's added to Onyo.

IMO, this issue can be closed.
