### ISSUE TITLE
Design and Implement faux serial numbers

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#111]
The information in the readme about faux serials is the following:
```
Assets for which the identity is not important receive a unique
faux-serial to prevent filename conflicts. These serials are
prepended with the word faux.
```

Currently I plan to just check if the serial field value is  `== "faux"`, and in that case call a function that generates a serial value which provides a *unique file name*, e.g. `laptop_apple_macbookpro.faux5252`. (I know we want the laptop serials to not be faux because the identity matters, it is just an example).

We talked about using something like https://docs.python.org/3/library/uuid.html. These generate fairly long names, so we should decide if we want:

- using them completely
- using them, but cut to certain length
- just generate an own unique but random number

How long should faux serial numbers be?

**Comment by TobiasKadelka** [comment]
Currently, I do not shorten them, so they will look like this:
`laptop_apple_macbookpro.faux78d7eb78-17bd-11ed-a855-b2e8ea761b9f`

**Comment by aqw** [comment]
A full uuid feels excessive. What I'm stuck on is how this should work in practice.

Ideally, we can just generate something, and feel secure that it won't collide (such as a uuid/guid). However, a full 32 characters feels unwieldy. Something like 8 or 10 "feels" sane.

I havn't done the math, but I would suspect that alphanumeric (case-insensitive) for 8 digits is secure enough for our purposes. While it may be weaker than a UUID, (16^32), 36^8 is still a lot of combinations.

The performance of checking for conflicts... that's another question. The information is contained in the file name, so we don't need to open each asset. We just need a list of files. Whether this is cheap enough to do every time `onyo new` is invoked is an open question, but should be easy enough to benchmark. Otherwise, we can operate on the assumption that there won't be any conflicts, and rely on `onyo fsck` (which should have a check for conflicts).

**Comment by TobiasKadelka** [comment]
In this case, I will shorten the added value.

`onyo fsck` has already a function that checks for file name duplicates, I use the same function during the faux serial creation, so that the asset name is definitely unique.

Obviously this might create problems in the long run, but I do not think it will be immediately problematic. Maybe I will do a test in the near future where I just create 10.000 assets or something with faux serials and check out how it performs?

There could be a fallback option that counts the number of faux serial numbers tried to be created with the current call of `onyo new`, and after x tries it just uses more digits...

______

There would also be the more simple option to just count up and use the first number that creates a unique asset name.
So when existing:
```
laptop_apple_macbookpro.faux1
laptop_apple_macbookpro.faux2
laptop_apple_macbookpro.faux3
```

Then `onyo new` would create next a `laptop_apple_macbookpro.faux4`, but a `laptop_lenovo_thinkpad.faux1`.
I do not necessarily like the look of that, but it would probably be better performance-wise and make sure that there would be no file name collisions when creating a million things of the same type.

**Comment by aqw** [comment]
> Maybe I will do a test in the near future where I just create 10.000 assets or something with faux serials and check out how it performs?

Yes, and I think this would be a good test to have, as a performance canary.

**Comment by aqw** [comment]
> There would also be the more simple option to just count up and use the first number that creates a unique asset name.

Yeah, I thought of this. But the "problem" is that onyo is decentralized. If everyone is counting upwards, there's a guarantee to be conflicts if two people add an asset with a faux-serial at the same time. With random serials, it's just a weak possibility.

**Comment by TobiasKadelka** [comment]
Regarding benchmark testing:

```
for i in {1..1000}         
do
   echo "a\na\na\nfaux" | onyo new -I shelf
done
```
