### ISSUE TITLE
`onyo new` asks for info to assemble the asset name, but doesn't store them in the asset file

### ISSUE THREAD

**Issue by aghisla** [psyinfra/onyo#124]
As now the metadata asked when creating a new asset are stored only in the filename, but I would store the information in the file as well. Of course that means that the filename and its contents could be edited separately, but it is an obvious infraction to the design, as it should never be necessary to change the type, vendor, model or serial number of an asset.

If not, it has to be accounted for when Onyo will perform faceted searches like "list all laptops with more than 16GB of RAM" - the information about type would be only in the filename (by position, btw) while RAM is stored in the file.

**Comment by aqw** [comment]
This is a general design decision for onyo, that information should only be stored in one location.

We certainly can revisit that, but I am very suspicious of such a direction.

The information in the filenames are (currently) called "pseudo-keys" (see #20 and #101), and will also be available for `get`, `set`, etc. This has no performance overhead (though arguably some complexity overhead), as the filename is already needed in order to open a file to parse its contents/keys.

**Comment by aghisla** [comment]
As long as it is the cleanest solution, I follow it, and I will adapt my templates (which included those metadata and made my first tests somewhat redundant).
