### ISSUE TITLE
files should be operated on a predictable order

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#135]
Many onyo commands allow multiple files as input.

While writting a test case for onyo set (`onyo set --recursive RAM=10` to update all assets) I noticed that the local tests are successful, while after pushing the tests failed. This was caused through the different order git looped over the assets while creating the diff like output, and solved with sorting the assets directly at the beginning when checking the input (the prepare arguments function, which exists in some form for all commands).

While this fix with sorting the input assets was done to make sure the new tests will work reliably, I am now wondering, if not all commands that can run over multiple assets/directories should sort them alphabetically.

The contra is obviously that a lot of internal sorting, especially when working with a lot of assets would impact run time.
the positive thing would mainly be to guarantee that onyo commands on the same assets would always work the same.

To be clear: the other commands/tests are not effected by any ordering problems, but I wanted to put out this question for thought.

**Comment by aqw** [comment]
I see this a bit differently, though related: the issue you're trying to resolve is whether files are operated on in a /predictable/ manner, not whether they are sorted.

IMO, when possible, the order specified by the user should be honored. e.g. if a user runs `onyo cat b a`, then they should be printed in the order of `b` and then `a`.

If a user specifies a folder, then I do see the /contents/ of that folder being sorted alphabetically (so that inode order isn't used). The user's intent is not clear, so us doing something predictable makes sense here (and, I would argue, is what a user would intuitively expect).

**Comment by TobiasKadelka** [comment]
Because we use now different functions and classes, the inputs and assets are used in a predictable (e.g. alphabetical) order. I will close this, and if there are other order-related topics a more specific issue should be opened.
