### ISSUE TITLE
TST: verify that onyo works from different locations with relative and absolute paths

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#142]
There are many combinations of paths that could be passed into onyo, with and without `onyo -C`, with and without absolute paths. That these work as intended needs to be implemented and tested, for API and CLI!

These are the different CLI situations Alex came up with that need to be tested for, once it is verfied that they work and are tested, they can be marked as checked:
- [x] repo_root arg_relative
- [ ] repo_root arg_absolute
- [ ] repo_subdir arg_relative
- [ ] repo_subdir arg_absolute
- [ ] repo_root -C root_relative arg_relative
- [ ] repo_root -C root_relative arg_absolute
- [ ] repo_root -C root_absolute arg_relative
- [ ] repo_root -C root_absolute arg_absolute
- [ ] repo_root -C subdir_relative arg_relative
- [ ] repo_root -C subdir_relative arg_absolute
- [ ] repo_root -C subdir_absolute arg_relative
- [ ] repo_root -C subdir_absolute arg_absolute
- [ ] repo_subdir -C root_relative arg_relative
- [ ] repo_subdir -C root_relative arg_absolute
- [ ] repo_subdir -C root_absolute arg_relative
- [ ] repo_subdir -C root_absolute arg_absolute
- [ ] repo_subdir -C subdir_relative arg_relative
- [ ] repo_subdir -C subdir_relative arg_absolute
- [ ] repo_subdir -C subdir_absolute arg_relative
- [ ] repo_subdir -C subdir_absolute arg_absolute
- [ ] outside -C root_relative arg_relative
- [ ] outside -C root_relative arg_absolute
- [ ] outside -C root_absolute arg_relative
- [ ] outside -C root_absolute arg_absolute
- [ ] outside -C subdir_relative arg_relative
- [ ] outside -C subdir_relative arg_absolute
- [ ] outside -C subdir_absolute arg_relative
- [ ] outside -C subdir_absolute arg_absolute

**Comment by aqw** [comment]
In general, I think we should follow Git's lead here. We can't do anything they can't do, and it largely makes sense to match them unless we have a good reason otherwise to deviate.

1) `onyo new <absolute path>/shelf` (so everywhere on the system with absolute path?)

This should work /if/ the CWD is in the same Onyo repo. Otherwise it should fail. This is the same as Git's behavior. This is why `-C` exists.

2) `onyo new <relative path>/shelf`

This is the same as `onyo new shelf` (which is a relative path). I see nothing controversial about this.

If you're instead asking if running `onyo new ../shelf` (from the onyo root) should work, then I think again that Onyo should follow git's behavior and fail here. Any path that leaves the onyo repo will result in errors (things can get very, very weird with symlinks).

```
aqw@hrududu in /tmp/testgit on git:master
❱ git add ../testgit/yope
fatal: ../testgit/yope: '../testgit/yope' is outside repository at '/tmp/testgit'
```

3) `onyo -C <absolute directory to onyo root> new <absolute path>shelf` (everywhere on the system, but additionally with -C?)

Git allows this:
```
aqw@hrududu in ~
❱ git -C /tmp/testgit add /tmp/testgit/yope
aqw@hrududu in ~
❱ git -C /tmp/testgit status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   yope
```

4) `onyo -C <rel path> new <absolute path>/shelf` (some weird combination?)

Git allows this:
```
aqw@hrududu in /tmp
❱ git -C testgit add /tmp/testgit/yope
aqw@hrududu in /tmp
❱ git -C testgit status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   yope
```

**Comment by aghisla** [comment]
I agree with following Git's behaviour. It is the least surprise for the user, and it is less translation work between Onyo and Git.

**Comment by TobiasKadelka** [comment]
I updated the initial comment of this issue with the list of different path situations Alex came up with, and I think these are all for the CLI.

**Comment by TobiasKadelka** [comment]
I ticked "repo_root arg_relative" because that is the default use case we always test for in the `tests/commands/`. In #351 I will start to add tests for the other szenarios!

**Comment by TobiasKadelka** [comment]
We changed the way onyo handles paths dramatically, the issues related to pathing should be solved.
Thereby I will close this issue; if something ever comes up again, we will file a proper bug-report.
