### ISSUE TITLE
design and name configuration files

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#19]

**Comment by TobiasKadelka** [comment]
I did not want to create a seperate issue for this now, but wanted to write a note here for later.

When the design of configuration files is done, `onyo new` should use them to read the specified list of reserved character per field. ATM the function just reads the fields and uses a list of reserved characters as specified in the code of the function itself, no config files are involved.

It might be valuable to think about the configuration file(s) *together with the template files*, since it might be wished that different templates have different "rules", and that rules are applied to the keys in asset names, but also the fields in the asset file itself, without having to edit both, config file and template file everytime.

**Comment by aqw** [comment]
This can be closed IMO. Configuration files are used in multiple contexts (generic, templating, validation). Any remaining issues should be opened as specific issues.
