### ISSUE TITLE
DEMO: generate an onyo demo

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#2]
I propose the clever name `onyo-example-repo`. It should have a dozen or so assets, a bit of history, etc. This way people can see what it looks like in practice.

This is most practically done after Onyo is actually written and functional. ;-)

**Comment by TobiasKadelka** [comment]
Since this issue is relevant for the planned onyo hackathon, I want to provide additional information about how the result should look like.

- One the one side, a shell script:
  - It contains a list of onyo commands to build a repository which simulates usage for a longer time period, e.g. a year:
      - start with an `onyo init` 
      - then beginning adding assets with `onyo new --tsv` (tsv needs to be created, too) to read an existing state of "owned devices"
      - `onyo new` for one/many new assets to simulate buying assets over time
      - `onyo mkdir` for adding new users and subgroups
      - `onyo mv` to give devices to users, subgroups, etc until the devices get retired
      - `onyo set` to update information
      - etc.

- And secondly, the `onyo-example-repo`:
  - The script described above should be in the main onyo repository (*this* repo, not the example-repo)
  - The script should be run by the github actions of this repository, and the created `onyo-example-repo` should be pushed to a separate and dedicated repository a.k.a. `onyo-example-repo` (on merge to main, not every time a PR is created)
  - On success, the created repo should be `git --force push`ed
    - the git history is a relevant part of onyo, so the `onyo-example-repo` must overwrite an existing example repository
  - The `onyo-example-repo` has to be mentioned in the onyo docs and readme

The Result is thereby a full workflow, which is shown in the script (and additional data like a tsv file) that provides users with a whole list of example commands and data, which is easily visible (via docs, readme, example-repo), and a repository which shows as well as possible what onyo provides as functionality, with files and history, when used to manage inventory.

**Comment by TobiasKadelka** [comment]
The repository will live here: https://github.com/psyinfra/onyo-demo
