### ISSUE TITLE
DOC: pseudo-keys

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#20]
This will be keys that are addressable, but not actually defined in the asset file itself.

- filename (readonly)
- fullfilename (readonly)
- make
- model
- type
- serial

**Comment by aqw** [comment]
Additional ideas:

- information pulled from git metadata:
  - `created_time`
  - `modified_time`
 - the filename/path in a format that is useful for commands such as `onyo rm` (#5)

**Comment by TobiasKadelka** [comment]
I think this issue should be closed, and if we want to add features like `created_time` and `modified_time` specific issues should be opened for it.

`onyo get` and future PRs will make the existing functionality for pseudo keys easier to handle, and The fields seem to be already documented under https://onyo.readthedocs.io/en/latest/concepts.html#asset-name-scheme

**Comment by TobiasKadelka** [comment]
This issue is drastically out of date. The only two parts still relevant are "add new keys", and "document pseudo keys".

Issue #678 describes the idea to rework how pseudo keys are addressed, and which new are wanted. Together with that work, the documentation will be updated. So everything relevant here is more up-to-date in #678.

Therefore I will close this issue, and all discussions will continue #678.
