### ISSUE TITLE
BUG: `-C` with a relative path results in widespread breakage

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#206]
Likely related to #170

**Comment by TobiasKadelka** [comment]
I thought long about how to attack this. I want to describe what I see as the only valid solution for this, considering all other parts of onyo, not just functionaly, but also when it comes to printing:
- all `Path`s in the repo class should be **absolut** internally. We need one or multiple functions (described in issue #325) that enable functionality for all commands and the repo class, and that take the `opdir` (either cwd, or provided with `onyo -C`, then normalized/sanitized to an absolut path) and connect that to the paths that might be provided as arguments via CLI or otherwise
- afterwards, all internal functionality works with the paths build like described above
- there needs to be one or multiple functions, used whenever printing happens to make paths relative from repo root
- the behavior here described will automatically be covered by tests already existing for some cases, but we definitely need new/additional tests to cover the varieties of different path-combinations (-C with absolut or not, paths given absolute or not, etc etc etc).

This is not just true for the paths of assets, but also for all other properties of `Repo`, I think including `Repo.root` and `Repo.opdir`

**Comment by TobiasKadelka** [comment]
We changed the way onyo handles paths dramatically, the issues related to pathing should be solved.
Thereby I will close this issue; if something ever comes up again, we will file a proper bug-report.
