### ISSUE TITLE
design template system

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#21]

**Comment by TobiasKadelka** [comment]
The templates should probably be connected to config files in #19 and I could imagine that there are no new commands needed, but instead they should be part in `onyo new` #3.

**Comment by TobiasKadelka** [comment]
From the #7 about designing `onyo fsck`:
- validate the contents of all files against their respective templates

As soon as the template system is designed/implemented, onyo fsck needs a functionality to verify the correctness of templates, when:
- templates change
- files change

**Comment by TobiasKadelka** [comment]
The PR #92 begins with the implementation of the template system.

The readme changes in #91 change the section "field validation" and mention customized templates.
When the way templating works is fully discussed, the information needs to be added and explained in the readme.

**Comment by TobiasKadelka** [comment]
From section file contents:
- TODO: template format
- TODO: validation
- TODO: template matching
- TODO: pseudo-keys

These TODOs are removed in PR #91 and instead moved into issues.
When these are clearly designed, explanations need to be added to the readme.

**Comment by TobiasKadelka** [comment]
I am thinking about how to do/add an `onyo fsck` function regarding "check assets against their template" and also "check after a template changes, that assets are still valid".

Basically, this needs some mechanism to identify/match an asset file at any later point in time against the template. The first thought would be something like adding a template field to each asset that just points to a template, but since templates are allowed to be renamed (like computer to laptop), this is probably not the best way.

**Comment by TobiasKadelka** [comment]
Another open question about templating is the whole topic of faux serial numbers.

**Comment by TobiasKadelka** [comment]
The template system is designed and implemented. Missing functionalities depend all on connecting assets, asset names, faux serials, templates, and their validation.
They are discussed at different places, so I close this.
