### ISSUE TITLE
BUG: `Repo` caches are not cleared on repo change

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#248]
The following caches are used by the `Repo` class:
```
self._assets = None
self._dirs = None
self._files = None
self._gitfiles = None
 ```

Methods that modify the state of the repo (`mkdir`, `mv`, `rm`, etc) should clear those caches.

**Comment by TobiasKadelka** [comment]
I am currently implementing this in the onyo API for the commands (and in the command `new.py`).

Alternative solutions would be to do this in `commit()`, but since we explicitely allow to not commit for quite a while, and in between to move, rename and do all the things, I feel like this would lead very soon to possible bugs.

The other alternative would be to just do this in the commands, but I feel like this is the same as asking users who use the API to always clear caches manually, which I do not like that much, too.

Thereby, the functions like `rm()`, `set()` etc should in my opinion also clean the caches when modifying them :)
