### ISSUE TITLE
TST: Faker support

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#254]
[Faker](https://faker.readthedocs.io/en/master/) generates fake data, and can be used with pytest. It can also be extended with our own data.

Faker could be very useful to populate test repositories with directories, asset names, and asset content.

**Comment by TobiasKadelka** [comment]
Is this idea still debated, @aqw ?

I see the theoretical value, but it adds days of work for unclear value, and that at a point in the further future. In praxis, we have a lot of pytests, and obviously since we use onyo already, we also test our use-cases in real life all the time.

If we ever actually want to spend time on revisiting how we test onyos corner cases, we can once again consider faker (or alternatives) as a fit, but right now I think we should close this issue.

If you disagree, please re-open immediately!

**Comment by aqw** [comment]
Yeah... I agree this can be closed.

The tests are due for a major normalization/overhaul. And perhaps Faker will be useful, but it's hard to know until that work begins and the scope crystalizes.

So +1 on closing. It's cart before the horse.
