### ISSUE TITLE
BUG: `Repo.assets` returns all `Repo.files`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#284]
This bug prevents inclusion of non-asset files (such as `README.md`) in and Onyo repo.

The fix for this is simple, thanks to `valid_name()` to filter. The problem is that `valid_name()` logs errors whenever it returns `false`, which leads to widespread test breakage elsewhere.

It needs to be assessed:
- should `valid_name()` log these and/or should the log-level be downgraded
- how to make sure `onyo new` still prints relevant error messages to `stderr`
- which tests should be updated/fixed to use valid asset file names (many don't, due to laziness on our part)

While out-of-scope, it's also worth keeping in mind the goals of #255 when fixing this.

**Comment by TobiasKadelka** [comment]
`def valid_name(logging=True):` as a default case, but from `Repo.get_assets(logging=False)` comes to my mind, since it does not change the current behavior, but enables the re-usability of the function.

That does obviously not work for #255, as long as we don't want to add this type of solution to all functions with logging, but I think might be part of solutions as a whole, when we want to use functions in multiple ways like here.
