### ISSUE TITLE
add `onyo new --set` 

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#287]
The relevant portions of #260 have been moved here:

We want `onyo new --set key=value asset` to have the optional flag `--set`, but also the possibility to not use it, while at least one (possibly multiple) asset(s) are needed, except when a `--tsv tsv.file` is specified, which disallows giving assets via command line.

It is unclear to me if this is possible without adding `--path` to `onyo new` (see #286), which I'm not thrilled about.

**Comment by aqw** [comment]
There are three options I see:

1) don't add `--set` to `onyo new`
2) add the `--path` flag to `onyo new`
3) examine the passed args to determine if they're a `key=value` pair or an asset.

1 would be a tangible loss in functionality, IMO. 2 would blur the command categories we just created. 3. is most intuitive IMO, but will make Tobias cry.

Thoughts? ;-)

**Comment by TobiasKadelka** [comment]
It makes me cry for sure, and it already does, since it is the current approach, and does still break the `onyo new --help`.

I see the argument against 2, but we do already have a `onyo new --tsv [path]`, so if there is a need to declare actively if it is about a tsv or an asset path, I could live with `onyo new --path warehouse/laptop_apple_macbookpro.123`

**Comment by aqw** [comment]
Another option:
- don't view this as a `set` of assets but rather using an ephemeral template.

**Comment by aqw** [comment]
2 and 4 are my current favorites.
