### ISSUE TITLE
Defining commit message headers

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#295]
The commit message headers should be consistent and give as much helpful information as possible for real use cases while acknowledging that we cannot always show _all information at once_. 

I focus on the commit message headers (the bodies can obviously contain all the information in the world).
Since 80 characters cannot do to much, the broader questions are "What information can we live without?", "What maximizes the value of the 80 characters?".

**1. "Full style"**

Every commit starts with the command name followed by `: `, and then in quotes the full name+path of assets modified, moved etc. This is close to the current style, but not all of these are actually implemented.

**2. "Shortened style"**

Instead of trying to present all information (which is not possible) we give "help to differentiate" between commits, to make it easier to find specifics when scrolling through (e.g. with tig).

I am currently intrigued by the idea to cut out all information that one would know or be able to guess from the rest of the commit message, and I think this "cutting out" idea will improve the visibility of information presented greatly, e.g. when changing contents, the assets are oftentimes more important than the paths, and when moving assets to a user just the `type` field is relevant.

------------

**Examples (currently):**
```
mkdir: 'ethics/Max Mustermann','ethics/Achilles Book'
new: 'warehouse/monitor_dell_PH123.86JZho','warehouse/laptop_apple_macbook.oiw629'
rm: 'admin/Karl Krebs/','ethics/Achilles Book/laptop_lenovo_thinkpad.owh8e2'
edit: 'warehouse/laptop_apple_macbook.9r5qlk','ethics/Max Mustermann/laptop_apple_macbook.9r32he'
mv: 'warehouse/laptop_apple_macbook.9r32he','repair/headphones_apple_airpods.7h8f04' -> 'ethics/Max Mustermann'
set: 'ethics/Max Mustermann/laptop_apple_macbook.9r32he','warehouse/laptop_apple_macbook.9r5qlk'
unset: 'ethics/Max Mustermann/laptop_apple_macbook.9r32he','warehouse/laptop_apple_macbook.9r5qlk'
```

**Examples (short):**
```
mkdir: 'ethics/Max Mustermann','ethics/Achilles Book'
new: 'monitor_dell_PH123.86JZho','laptop_apple_macbook.oiw629'
rm: 'Karl Krebs/','laptop_lenovo_thinkpad.owh8e2'
edit: 'laptop_apple_macbook.9r5qlk','laptop_apple_macbook.9r32he'
mv: 'laptop','headphones' -> 'Max Mustermann'
set: (RAM,USB) 'laptop_apple_macbook.9r32he','laptop_apple_macbook.9r5qlk'
unset: (RAM,USB) 'laptop_apple_macbook.9r32he','laptop_apple_macbook.9r5qlk'
```

- `mkdir`: the whole path(s)
- `new` and `edit`: just asset(s) without path
- `rm`: always the highest level (either the asset deleted, or the highest folder like user or group, without complete path)
- `mv`: just the `type` field of source(s), and the highest level of destination
- `set` and `unset`: just highest level (either assets or folders), but additionally with keys set

**Comment by TobiasKadelka** [comment]
While trying to figure this out, I had some further questions.

What actually the max. length of commit messages should be:
- 80 chars
- 60 chars
- flexible number in onyo config file

Should "user specified commit messages" completely overwrite the existing ones, or should they still contain the command, e.g. `onyo mv -m MSG asset user` should create the simple and obvious MSG, or should it still look like `mv: MSG`?
I think a complete overwrite is what is assumed (and done by git) but wanted to ask for other opinions anyways.

**Comment by nhjjr** [comment]
The primary question we should answer is: What do we want people to use `onyo history` for?
 
We simply cannot guarantee the character limit if we are going to put asset names in there. Even the name without its basepath can be so long that useful information will easily exceed the character limit. For example: `rename gaminglaptop_microsoft_surfacebook1703.uoewrfguho to laptop_microsoft_surfacebook1703.uoewrfguho` is 103 characters. The information is also redundant, in that all files/contents affected by the commit can be seen in the detail view. Since `onyo history` opens `tig`, you can use `tig` commands to search (and more). Furthermore, if a user is interested in the history of a single file, they can run `onyo history file`.

Dynamic (potentially lengthy) information that is not available from the detail view in `tig` can be put in the long message. However, I would reserve this for user comments. This would necessitate adding something like `--comment` to any command that performs a commit, in addition to `-m` to let users overwrite the default commit message (which I would not character-limit; if a user wants custom commit messages what guidelines to follow becomes their problem).

This would give us a 'very' brief commit style:
  - `move 6 assets`
  - `set 3 keys in 6 assets [commented]`
  - `create 1 asset`
  - `create 5 directories [commented]`
  - `rename 2 assets`

The `[commented]` part of the commit message indicates there is a long message they can read if they view the details of that commit.

In the end it is simple. `onyo history` allows you to see datetime, author, command associated with the commit, and number of entities affected. Usually enough identifiable information to find that commit you're looking for. For anything more complex, use whatever `tig` ships with.

**Comment by TobiasKadelka** [comment]
I do disagree with the whole idea that, because the commit history can't always display all information at once, that we completely remove all the information that makes it easy to identify a commit. That does not just quickly gets messy for a single person, but especially for our use-case when two people giving out hardware (or having to register newly bought stuff) it should be possible to see quickly something like "ah, Niels and Tobias got their devices today already" or "the new laptops lying over there have already entries". 

That style you describe is what we had in the beginning (and still have in the demo for some commands), and as soon as you have a list from 4 times the same command in a row it is just not nice to use.

So in general, I do prefere my solutions. I could however imagine that we cut of at a certain message length and add the number of modified assets instead at the end, so that people can easily see in the history when many assets at once were modified or moved.

**Comment by TobiasKadelka** [comment]
I shortened the initial description of this issue and added instead more explicit examples.

**Comment by nhjjr** [comment]
So you want users of `onyo history` to see relevant information at a glance? In that case you should get rid of commit length altogether and use the long version (or list the arguments of the command given). For example, in a truncated/short version you wouldn't be able to see if both of us got new devices today if each of us gets a batch of 10 assets assigned to us through one command (e.g., `onyo move warehouse/laptop_x_y.serial warehouse/mouse_x_y.serial warehouse/usb-stick_x_y.serial warehouse/wifi-dongle_x_y.serial warehouse/keyboard_x_y.serial warehouse/hub_x_y.serial warehouse/hdmi-cable_x_y.serial dnp/niels`). It is even worse if such a scenario happens rarely, because then a user may start to rely on being able to search for the destination using `/` in `tig`, and simply not finding it because it was truncated.  The short commit scheme as suggested also depends on the asset naming scheme. Only one of the keys available in the name is used, but what if the user changes the naming scheme? Currently `type` (first word in the name) is used as a shorthand, but what if that is replaced by `institute`? Showing that multiple `inm7` assets were moved to a user isn't going to make things clear. Avoiding this case scenario either means restricting the custom name scheme, or adding config bloat for commit message formatting.

Despite thinking the long version is better than the short version, I'm still not a fan of it. It will clog up the commit history with a lot of redundant information that can be accessed and assessed through a variety of commands (e.g. `git log --stat | tig` or `git diff HEAD~20 | tig`, which can even be limited to a file or folder).

The ease of identification of a commit should also be much easier when users can merge commits (e.g., merging and identifying a few `mkdir` and `mv` commits as 'onboarding tobias'), and if no custom commit message is given then merging similarly typed commits just requires incrementing a counter. 

Lastly, rather than creating unwieldy commits, we could also identify potential search and identification bottlenecks and improve the functionality of `onyo history` instead. As I said, the information that is suggested to be put in the commit message already exists in the commit itself.

**Comment by TobiasKadelka** [comment]
I am thinking about adding the number of changed assetse.g.:
`set [2]: (RAM) 'laptop_apple_macbook.9r32he','laptop_apple_macbook.9r5qlk'`
`new [2]: 'monitor_dell_PH123.86JZho','laptop_apple_macbook.oiw629'`

Though that creates for almost all commands the obvious question "how would this count folders?".
Especially for commands like `onyo rm` and `onyo mv` the numbers might be weird when counting the actual assets, when just a folder would be moved or deleted. Because of the `.anchor` files, I think the most reasonable way to implement this, is to add `len(repo.repo.files_staged)`, which would count each moved asset +1, and each subfolder +1, so moving an "empty" `./dataplatforms/tobias` with existing `./dataplatforms/tobias/home` to `./hhu/dataplatforms/tobias` would count as 2 (once for the anchor in `tobias` and another anchor in `home`).

Re: character limit, I looked into the demo commits again, and I think the git browser version just displays 60 characters and then automatically breaks the line with [...] add the end.
This looks fine enough I guess, so I would actually just think about if the solution we would implement is good enough for commands like `tig` and `git log`. For this, I am actually wondering if ignoring the character limit is not a reasonable solution. Alternatives would be to automatically line break every x characters.

Though I think this does not remove all the ideas I discussed above to shorten/cut out certain information, since at first glance there is still just limited space.

Indeed, I tried around a bit and think the idea to just add the `type` field is by far the weakest from my ideas, especially because the `mv` command might be used a lot, so it might matter after all.

**Comment by TobiasKadelka** [comment]
> So you want users of `onyo history` to see relevant information at a glance? 

Yes, as far as possible I want to make that possible. :) This issue is meant to discuss the best way to do that for most of the cases, so that when doing many similar commands in a row, it does not look like the demo repository commits, where it is hard to find an overview.

> In that case you should get rid of commit length altogether and use the long version (or list the arguments of the command given).

The lists of arguments is varying a bit (for example depending on the location) and comes with some problems (e.g. with shell completion), but otherwise these points are worth considering, I adressed them in the comment above.

> ... can be accessed and assessed through a variety of commands (e.g. `git log --stat | tig` or `git diff HEAD~20 | tig`, which can even be limited to a file or folder).

That is technically true, but the general philosophy of onyo is to try being able to do anything without git when the user just uses onyo commands (especially because one can do anything that onyo offers with git, when trying enough, so `onyo`s job is making it not necessary).
So while these more complex commands can give more information and be helpful, I still see a lot of value in the onyo history being as good as possible as often as possible.

> The ease of identification of a commit should also be much easier when users can merge commits

Yes, but this functionality does not exist and might not exist before the first two users test it, because there are some bugs and missing core-features I want to work on first. Also, costumized commits (#294) will make this easier, too, but I think these should be actual features, and not necessary to make the history worth looking at.

> Lastly, rather than creating unwieldy commits, we could also identify potential search and identification bottlenecks and improve the functionality of `onyo history` instead. As I said, the information that is suggested to be put in the commit message already exists in the commit itself.

I consider improving the commit message headers as exactly that - the identification of the bottleneck (which is having to look into commits to see clearer what they did), and as improving the functionality of `onyo history` :)

-----------

Like I said above in this issue, I am aware of the practical limitations, and all solutions come with some assumptions (even the assumptions are "the user can look into the commit, the message does not need to display more then the command name"). Still, my main goal is to make the history at least as helpful as possible for most situations, and I think the current way, which is inconsistent between commands, and oftentimes present almost no information, is easy to improve with almost all of the proposed solutions.
