### ISSUE TITLE
design `onyo new`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#3]
This is to create new assets. Current idea is:

```
onyo new warehouse
<type>*: laptop
<make>*: lenovo
<model>*: T490s
<serial>*: abc123
<spawns VIM, the above fields are pre-filled. The user edits remaining fields>
<writes out to shelf/laptop_lenovo_T490s.abc123
```

Additional ideas involve optionally "copying" another asset as a seed.

**Comment by TobiasKadelka** [comment]
The current ```onyo new <folder>``` just works, if the folder already exists, otherwise it prints out an error-message.
Should onyo create the folder, if it does not already exist?

Cons:
- When doing a typo ```onyo new sshelf```, it would create the wrong folder, instead of adding the new asset to the wanted place.
Pros:
- currently there is no way to use onyo to create a folder, folders need to be created with the non-onyo ```mkdir <folder>```. When onyo creates them, it is possible to manage the repo fully with onyo. 
- empty folders are not tracked in git, but when onyo creates them together with an asset, they would never be empty and can always be tracked.

I could imagine a flag would make sense:
```onyo new --create-folder shelf``` or --force or something like that, so the user has to actively decide to create a new folder, but is able to do it with onyo, if wanted.

**Comment by TobiasKadelka** [comment]
I am wondering, if the user should actually fill out the remaining fields in vim, like specified and wanted to write down my thoughts about alternative possibilities in connection to templates and config files here.

Depending on how we do the matching with templates and config files, and allow Rule-specification in them something like this could work:

```
onyo new shelf
<type>*: laptop
<make>*: lenovo
<model>*: T490s
<serial>*: abc123
<ram in GB>*:asdf
onyo info: please enter number
<ram in GB>*:16
<writes out to shelf/laptop_lenovo_T490s.abc123>
```

On the *pro* side: the reading of values could be more robust and better specified, since rules can be defined in the templates and config files, and values would be read one by one.
Also `onyo new` would be easier to use from another program (handling opening/closing of an editor from another program is tricky, CLI input is way easier), and I think this would be also easier for the user, when working a lot with a templates for something like laptops, where the fields are often the same or similar.

*Cons* would be, that when additional fields would be needed, that are not specified in templates, one would need to use `onyo set/edit` separately. When no templates are used, the files would be created empty.

**Comment by TobiasKadelka** [comment]
`onyo new` is implemented and documented for quite a while.
