### ISSUE TITLE
BUG: `KeyboardInterrupt` and `EOFError` can leave repository in a non-clean state

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#301]
Some commands, but especially `onyo set` and `onyo unset` leave the repository in a dirty state, when the user uses CTRL+C while a user-response is requested to save the changes.

One can add in python `except (KeyboardInterrupt, EOFError) as e:` and I think we should figure out what the correct way is to make sure that a user-interrupt or an EOFError gets handled correctly.

-------

We might simply add the `KeyboardInterrupt` to the function `request_user_response()` (and maybe at other places?) and interprete this as a valid response, because currently when the user does Interrupt onyo, it will leave the repository in a "dirty" state, instead of restoring before leaving.

About the `EOFError` I am not as sure as I am about the KeyboardInterrupt, it would provide the same value of not leaving the repository in a dirty state, but at the same time, when writing an onyo script, we might not want to run the next commands, but leave with the Error?

Alternatively, we might throw our own type of error instead, restore the repository, and then do a sys.exit(1).

**Comment by TobiasKadelka** [comment]
The biggest problem I see, and this is not specific for this issue, but possibly most urgently in this context, is that when we would in `request_user_response()` add 
```
except (KeyboardInterrupt, EOFError) as e:
    repo.restore()
    sys.exit(1)
```

That this would lead to problems when the user has unstaged/uncommitted changes in the repository. Our fscks currently should prevent that from being a problem, but since we want to modify that behavior, and even allow `--skip-tests` later, this might lead to information loss. Maybe we need to upgrade the restore-function to make sure it just restores assets or something, not everything. 

In general I think there should happen *something*, to leave the repository not in a weird state, but we should probably discuss in a more complete way, what exactly is the behavior we want, and with which downsides we can live.

**Comment by bpoldrack** [comment]
FTR:

I think the biggest issue here is the internal flow that actually does changes before it knows that it should do them. If user confirmation is required: Get the confirmation first, not write and rollback. Same for dryruns: Something called a dryrun is not supposed to actually change anything. Ever. Doing it for real and rolling back is not what a dryrun is for.
Same flavor again for collecting a multitude of changes: Often things are changed and staged long before we know we can actually perform the operation. So, it's spending time on doing this onyl to then spend more time rolling it back to then eventually fail, because an input argument couldn't be acted upon.
Instead: Assemble a "TODO-list" and only when it's complete - act on it.


Otherwise, I agree: things like `KeyboardInterrupt` need to be accounted for, but currently the problem is bigger than it ought to be - independently on how such an exception is handled.

**Comment by TobiasKadelka** [comment]
In `onyo/lib/command_utils.py` we now use:
`from difflib import unified_diff`

This replaces the "editing" of files before the user verified that changes should be written. This should solve the underlying issue; thereby I close this issue.
