### ISSUE TITLE
Add `Asset` class (WIP/DISCUSSION)

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#325]
I see two ways to do this right, in both cases I see it as an absolutely necessary requirement to solve #206 with this effort, for all different cases, and enable that printing of paths will still work always from `repo.root` and `repo.opdir`.

One of these should be done:
1. have a more general class for `onyo path`s (which e.g. both have a `Path`, and own checks for validity), and then to classes `Asset`, `Directory` (and possibly `File` or some others) that inherit from these and overwrite, especially validity (either dir needs `.anchor`, or assets must be valid YAML, etc).
2. add just an `Asset` class, and directories stay `Path`s (just changed to absolut)

In my opinion, if the asset class gets implemented, it should directly be used by all commands, all functions in the repo class, and all tests. This helps with both, keeping Onyo consistent, and also being sure that the changes solve the requirements we have for the `Asset` class. This will probably mean to rewrite at least some parts of everything, since basically everything in Onyo works with assets in some form.

I know this is then automatically a massive effort which blocks all other work from happening, and that is why I want to describe all that is needed to implement this change here, so as to enable a discussion based on *something* and have the results of it collected here! When the discussion is then ended and it goes to implementing, this issue will work as a TODO list to realize the changes.

While development, I think we want to work each in our own forks (like we do now) and merge from there all into a new separate `psyinfra/onyo`-branch (e.g. named `asset-class`), that in the end just gets merged into the `main` branch.

------------------------

IMO the `Asset` class will just handle information (e.g. path and contents). There should be no `rm` for deleting an asset, no `mv` to move the location, etc etc, these kinds of operations should still be done in the `Repo` class.

Properties (for the new asset class):
- path: `Path` for the YAML file (this should be absolut, so as to enable easy solving of #206)
  - I think all paths have to be *absolut* (like I describe in #206), functionality needs to be provided that does this correct for different opdirs (either with `onyo -C <path>` or just the cwd)
  - one or more functions are needed (probably in repo class. Possibly in both, repo and asset) that makes it easy to print paths relative to `repo.root` (e.g. for commit message) and to `repo.opdir` (for prints to terminal e.g. for listing paths)

- contents: `ordered dict` that caches the contents
  - contents can be cached, I think the clearing of `Repo.assets` is sufficient for the beginning (even though not runtime efficient)

----
CHANGES IN EXISTING CODE

1. Code from `lib/`:

A lot of functions (and their tests) need to be moved from `Repo` into assets, and possibly modified.
- `Repo._read_asset()`
- `Repo._write_asset()` 
- some `fsck`s, possibly? (pseudo-keys, asset-unique, asset-yaml, asset-validity)
- `generate_faux_serials()`? (Maybe `Repo` is already the right location, since it needs awareness of all asset names)
- `valid_name()` and probably some other pseudo-key related functionality (this should make it easier to have flexible name schemes)

Some of these functions should still be in some form in `Repo`, but `Repo` should then just check that the assets exist in the repo, and then call the function of the Asset objects.

Not all CLI commands (from `onyo/commands/*.py`) are equally effected.
1. The commands from this list should use the Asset class, because they handle contents:
- new
- get (and Filter :P)
- set
- unset

2. These commands should not use the `Asset` class, they work just with `Path`s, `Repo` or else:
- config
- fsck (all asset-stuff will be handled in `Repo`, not in the `commands/fsck.py`)
- history
- init
- mkdir
- mv
- rm
- shell_completion
- tree

3. These I don't know, but probably at least not in the beginning?:
- cat
- edit

Additionally, other parts of onyo need to be absolut, too, to make this work for the whole code base in a consistent way. The properties of the Repo-class need to be changed, and probably Exceptions need to be updated.

**Comment by nhjjr** [comment]
So these are my RFC notes on how I think the asset class should be implemented.

# Separate Methods
The `fsck` methods often use contents outside of the scope of the asset, but within the scope of the repository. The asset class should have validation to ensure the content it creates is valid, but there should be a separate `fsck` approach (see `FileSystemCheck`).

Note that things like `valid_name()` are more complicated than just checking whether the pseudo-keys are used. We also need to check for duplicate names throughout the entire repository, which an fsck does but an Asset object shouldn't. We shouldn't provide this kind of repo information to the asset class; this is a mark of a [Big Ball of Mud](https://en.wikipedia.org/wiki/Anti-pattern#Software_engineering_anti-patterns) anti-pattern (e.g., "information is shared promiscuously among distant elements of the system)". This is currently already a problem, because the `Repo` class holds methods that are not repo specific (e.g., `_read_asset` and `_is_protected_path`) and therefore require other functions to have repo access when they shouldn't.

After much thought, there shouldn't be an `OnyoPath` object. Aside from determining whether the object is protected, and (superfluously) adding properties for absolute and relative-to-root paths there is no added functionality here. Instead, functions that deal with paths should be in `onyo.lib.fs`, which will also house the `FileSystemCheck` functionality. Crucially, the `_is_protected_path` function should not be in the repository _unless_ it is repo-specific (e.g., there are configurable protected paths; but this is not a functionality I am aware of).

# Asset Object
The asset class has the following properties:
  * `contents: Optional[dict]`: This is `None` if the contents have not been loaded, `{}` if the contents are empty, and a dictionary with key: value pairs if it has been loaded.
  * `name: AssetName`: The name of the asset
  * `path: Path`: The path given as input
  * `repopath: Path`: The path relative to the repository root
  * `abspath: Path`: The absolute path

The asset class has the following methods:
  * `__init__(path: Path) -> None`: This sets up the class with information from the given path, e.g., creates a `AssetName` object for `self.name`, then constructs the various paths. 
  * `load() -> None`: This loads the contents of the asset into `self.contents`
  * `save(dest: str | None = None) -> None`: This creates or overwrites a file with the given `self.name`. If `path` differs from the name (i.e., the name was edited), then it will rename that file and overwrite the contents. If contents is empty, it writes out an empty dictionary. If no file exists, it will create a new file with the given properties. If a `dest` is specified, then the entered `self.path` will be moved to a new location. Note that `dest` is not allowed to be a filepath, it must be a directory that already exists (non-existing dirs should be taken care of outside of this function).
  * `get(key: str, default: Any = None) -> Any`: This performs a `load()` if `contents is None`, and then returns the value of the given key if it exists, or the default if it doesn't exist. If no default is given and it doesn't exist it raises a `ValueError`, and if the asset doesn't exist on disk it raises a `FileNotFoundError`.
  * `set(key: str, value: Any) -> None`: This performs a `load()` if `contents is None and self.abspath.exists()`, and then changes the key: value pair in `self.contents`. If the file does not exist, it creates a new dictionary and fills it with its very first key: value pair. This is purely a helper method that validates the given input, and can also be used to set pseudo-keys. It is entirely possible to not use this method and edit `contents` directly, but then input validation has to be performed manually.
  * `unset(key: str) -> None`: This performs a `load()` if `contents is None and self.abspath.exists()`, and then deletes the key: value pair matching `key`. If the file does not exists and `not self.contents` (e.g., it is `None` or `{}`) it will raise a `ValueError`. The pseudo-keys cannot be unset.

# AssetName object
This is a class that deals with asset names. These name template can be configured, or use the default 'type', 'make', 'model', 'serial' layout.

It has the following properties:
  * `name: str`: returns the asset name `laptop_apple_macbookpro.123`
  * `parts: dict`: returns a dictionary of name parts, where each key lines up with the configured template or the defaults

It has the following methods:
  * `__init__(name: Optional[str], **kwargs)`: defines `self._name` based either on a given full name (e.g., `laptop_apple_macbookpro.123`), or a full list of valid pseudo-keys (e.g., `type='laptop', make='apple', model='macbookpro', serial='123')`, where serial is optional. If not given, a new serial will be generated immediately. A `ValueError` is raised if `name` is given but not valid, if `name` and `kwargs` are given, if `name` is not given but `kwargs` are invalid, and if neither `name` nor `kwargs` are given.
  * `__str__` that returns the asset name constructed from its parts, e.g. `laptop_apple-macbookpro.serial`
  * `__repr__() -> str` that returns the same as `__str__`, so that we can pass an `AssetName` object as if it were a string.
  * `reserialize()`: Give the asset a new randomly generated serial
  * `set()`: set a key to a new value, e.g., `set(make='dell')`
  * `get()`: get the value of a key, e.g., `get('make')` returns `apple` (or `dell` after the set)
  * `validate()`: Checks whether the currently set parts can form a valid name, but crucially does not check the entire repository for duplicate asset names. That is outside of the scope of this function.

Initializing this class with an invalidly named asset should raise a warning. What exactly is the right approach is unclear to me. Should we allow saving assets with invalid names? If not, the `AssetName` object can automatically add a placeholder, e.g., `unknown` or `none` to missing name parts. However, there can also be names that are invalid because they have too much information (e.g., `laptop_apple_macbookpro_broken_repaired.123`). We could tackle those cases by replacing excessive underscores with dashes or other legal characters, appending them to the last pseudo-key prior to the serial (model). Currently we have no solution for this.

# AssetContent object
I understand this is a controversial abstraction. Its use is predominately in decoupling asset contents from the asset class, and allowing us to modify (or create multiple versions of) content structure separately. This class should deal with content interpretation and validation regardless of whether the contents are loaded from JSON, YAML, or whichever format we decide to add.

I purposely left this underexplored. I simply haven't had the time, but I also think that for now using `Asset.contents` as a dictionary will suffice, and can be refactored later without much issue.

# Use Cases
Creating a new asset is done as follows:
```
asset = Asset(path=Path('foo/bar/type_make_model.serial'))
asset.set(key='foo', value='bar')
asset.save()
```

If we want to move an asset, we can do:
```
asset = Asset(path=Path('existing/asset/foo_bar_baz.123'))
asset.save(dest=Path('new/location'))
```

If we want to rename an asset, we can do:
```
asset = Asset(path=Path('existing/assetr/foo_bar_baz.123'))
asset.name.set(make='dell')  # change the make
asset.name.reserialize()  # change the serial
asset.save()
```
Note that this should be how `Asset.set` deals with changing pseudo-keys as well, so the calls to `asset.name.set()` in this snippet are functionally equivalent to using `asset.set()`. There is, however, no reason to make `asset.name.set()` private, because it can be used when constructing an asset's name and appending it to a `Path` to create a new asset.

If we want to change an asset's contents, we can do:
```
asset = Asset(path=Path('existing/assetr/foo_bar_baz.123'))
asset.set(make='dell')  # same as `asset.name.set(make='dell')`
asset.set(foo='bar')  # non-pseudo-key, changes contents dict
asset.save()
```

If we want to change multiple asset keys, we can do (note that the map syntax may be off, I did this off the top of my head, but rest assured there is a working solution that is equally clean):
```
asset_name = AssetName(type='laptop', make='apple', model='macbookpro')
target_path = Path('existing/directory')
new_asset = target_path.joinpath(str(asset_name))
things_to_set = {'foo': 'bar', 'make': 'dell'}
asset = Asset(path=new_asset)
map(asset.set, *things_to_set.items())
asset.save()
```

Alternatively, we can use the following to determine asset name:
```
asset_name = AssetName('laptop_apple_macbookpro.123')  # serial is optional
things_to_set = {'foo': 'bar', 'make': 'dell'}
asset = Asset(path=Path(asset_name))
map(asset.set, *things_to_set.items())
asset.save(dest='existing/directory')
```

We even have the option to do the following:
```
asset = Asset(path=Path('existing/directory/laptop_apple_macbookpro.123'))
things_to_set = {'foo': 'bar', 'make': 'dell'}
map(asset.set, *things_to_set.items())
```

Then there's also the following, which automatically passes the path to `AssetName` for formatting and validation. However, this means that manual validation and setting cannot be done before generating the `Asset` object:
```
asset = Asset(path=Path('laptop_apple_macbookpro.123'))
...
```


If we want to get multiple keys from an asset, we can do:
```
asset = Asset(path=Path('existing/asset/foo_bar_baz.123'))
things_to_get = ['foo', 'make']
results = map(asset.get, things_to_get)
```

# Conclusion
All other functionality that deals with assets can deal with them in this way. Note that we should not shoe-horn CLI patterns in here, nor should we use CLI styling. We shouldn't send `'key=value'` input to this class; it is up to the CLI command to separate this and use `Asset.get` or `Asset.set` appropriately.

This approach gives us optimal flexibility, without going out of scope for the asset class itself.

**Comment by TobiasKadelka** [comment]
During a meeting, it was decided, that an `Asset` class offers nothing, that can't already be done with the functions `Repo._write_asset()` and `Repo._read_asset()`, so the effort of refactoring big parts of the repository for an `Asset` class is not justified. Therefore, this issue will now be closed.

The read/write functions will probably be moved outside of the repository to make it possible to read the contents of an asset without a Repo object.
If additional functionalities are later identified, that actually profit from such a class, the discussion can be reopened.

**Comment by nhjjr** [comment]
I think you're misrepresenting what was discussed in the meeting. It is not that the `Asset` class offers nothing that can't already be done, but that it is currently unclear how that asset class should be designed without 'overdesigning' it.

Instead, we should first relocate functions (e.g., `Repo._read_asset()`, `Repo._write_asset()`, `Repo.valid_name()`, `Repo._is_protected_path()`, `Repo.pseudo_keys`) outside of the Repo class, as well as the to-be-created `get_pseudo_keys_from_asset_name` (or some shorter name ;)). There will likely be more cases where a method inside `Repo` has uses outside of it.

Once this has been done, eventually we'll see whether (and how) an `Asset` class should be created.
