### ISSUE TITLE
Define usecases to test for

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#345]
Based on the usecase discussion in #335, here I will try to boil it down to actually testable cases.
Opening post is intended to be edited to flesh it out. As verbal description first. Meant to be converted into actual operations (and a TODO for each case).

Usecases
========

New group/location
-----------------------------

- new inventory folder: `onyo mkdir <location>`

New member
--------------------

- add a folder: `onyo mkdir <group/user>`
- assign asset(s)
    - find something in warehouse 
    - move from warehouse  `onyo mv <asset> <group/user>`
    - add directly to user? (new purchase)  `onyo new <group/user/asset>`

Member moves
-----------------------

- first, probably query what member actually has
- assets may need to move to
  - group or room (stuff left behind)
  - move with the member
  - move to warehouse
  - move from warehouse

Member leaves
-----------------------

- What does member have assigned?
- assets may be found "lost" on this occasion?
- assets go back to warehouse
- assets may be retired
- remove member

Member/group/room changes name/"identifier"
-----------------------------------------------------------------------

- rename respective folder

Add FZJ inventory number to existing assets
----------------------------------------------------------------

- find asset in question (possibly needs interaction with member)
- add key value pair

Asset changes properties due to upgrade/repair/whatever
------------------------------------------------------------------------------------

- change value of a key
- add a key-value pair

Retire asset
-----------------

- What needs to be found?
- Move asset to "retired"

Remove an asset
-------------------------

- actual removal

New asset(s) purchased
----------------------------------

- add to warehouse

Queries
-----------

- What is available in warehouse/on shelf?
- Everything with an FZJ inventory number
- Where is an asset? Based on:
  - Hostname of a laptop
  - pseudo key(s)
  - inventory number
- All assets within a subtree (group, room, person, whatever), that also match some filter criteria
- What is the history of an asset?
- All assets not in "retired" location of a certain type, that match something like `"20160101 <= build-date <= 20171231"`
- Apple recall on battery of all 13" MacBook Pros built between 2016-2017

Validation
---------------

- unique asset names
  General note: This should probably be based on resolved paths in order to allow symlinks.
  For example: part time association with different groups and asset search point may differ based on context
- valid yaml
- clean worktree
- Configurable constraints on actual metadata?
  - criteria for keys within assets?
  - criteria for keys across assets?
  - limit such criteria to subtrees?
  
 Configuration
---------------------

That's entirely uncovered by discussion so far.

**Comment by aghisla** [comment]
My notes, in order (what I don't comment on looks fine to me):

**New member, add directly to user? (new purchase)** : add directly to user does happen but not because of new purchases (at least not anymore; my laptop was indeed bought and shipped directly to me, but since I manage laptops, that never happened again, we always get the machine first and set it up, then give it to a user). There are various valid reasons for assigning equipment directly to a user from somewhere else than the warehouse or shelf, so in any case it deserves to be in an example/test. An example is one group having a spare laptop for interns who gets given out for one or two months then gets back to the group. When needed, we can ask the group leader where the laptop actually is.

**Member leaves**: as a subset of member moves, the initial query is the same. About finding lost assets, it is an out-of-Onyo problem, and could be explained to Onyo by moving the lost asset in a "lost" folder. That can happen with stolen equipment too and I plan to use the same logic but a "stolen" folder.

**Add FZJ inventory number to existing assets**: yes, finding the asset in real life would be querying Onyo about the folder/path, as usual. The interaction afterwards and the handling of the sticker happen outside of Onyo.

**Asset changes properties due to upgrade/repair/whatever**: this is an in-file edit of one or more properties in case of laptops and/or small repairs that are otherwise not tracked (Thinkpads can get a different keyboard layout by swapping the keyboard unit, so it's ok to only edit the keyboard layout property; MacBooks have a fixed keyboard unit so that is not the case, repairs on those machines are to restore functionality and not to change features - their repair would be tracked as a move to the "repair" folder and if there is any document or code they can be mentioned in the custom commit messages of the move).

In the case of the cluster, machines get bought as units, but parts get bought separately and are relatively often moved among machines. Therefore it makes more sense to see a machine as a folder (named after the hostname), containing a base asset file of the chassis or motherboard (what is more unique) and N files of the extra parts. There may be more thoughts to spend on this but when we brainstormed it was the cleanest approach that makes use of the folder structure (and I still think it is).

I'll send this already; will write later about the other half of the list :)

**Comment by aghisla** [comment]
(Second episode)

**Retire asset**: what needs to be found is the asset file or folder, searching by hostname (for objects that have it) or FZJ inventory number or serial number, or person in possession of the asset (whatever is easier to get/read, we cross check anyway before commit)

**Remove asset**: I know it's possible to query git history for files removed from the filesystem, but for our purposes I would keep the files even when the asset is gone, unless it makes no difference for me as user.

**New asset(s) purchased**: to be picky, our use case is "New asset(s) delivered" - I would let the virtual warehouse mirror the real-life warehouse. Onyo may or may not be informed about booked assets that are not delivered yet, and if so, in subfolders of the warehouse.

**Queries**: it can get long so I'll make a separate comment.

**Validation**: as basic validation I upvote the unique asset names, valid YAML (syntax), and clean worktree (there could be exceptions but I prefer Onyo to ask to cleanup irrelevant files rather than stay quiet on something it interpreted as OK). For the validation of content I think that Onyo should offer the option to specify custom, per-repo rules, but should not enforce or provide anything by default.

**Configuration**: I can't think right now of anything more than basic git configuration settings, and I guess that depends on the implementation of Onyo itself.

**Comment by bpoldrack** [comment]
@aghisla 

Thanks much!

Re Remove asset: I would assume actual deletion in case of some screwed up data entry is still a thing, right? Obviously, one doesn't necessarily need onyo to achieve it, but it would provide a consistent history of what was done how (and hopefully why).

**Comment by bpoldrack** [comment]
> I see advantages for both so I can't pick one yet :)

No need to pick. We can have both. :)

**Comment by bpoldrack** [comment]
PR #357 provides the first implementation of a CLI based flow involving the described usecases.
Python interface should obviously allow for the exact same usecases, but is not yet tested.

Implementation of CLI tests led to following issues:

- desired history is actually not yet well defined as far as I'm aware. Respective assertions are only useful when we've settled on what is wanted (TODO: dedicated issue, link here)
- `get` does not seem to have the ability to exclude subtrees from matching (as in everything except `retired` and `lost` or something like that) (TODO: dedicated issue, link here)
- `get` does not yet allow to return the asset paths only. Throughout the workflow the matching asset path(s) are almost always what is wanted in order to feed it to the next operation. Via CLI that currently means to manually copy that part of the output into the next command call or do some string slicing/parsing magic in addition rather than just have something along those lines: `onyo set -k fzj_inventory_number=x -p $(onyo get --filter serial=y)` when having a serial number `y` that finally got an FZJ inventory number and needs setting now. (TODO: dedicated issue, link here)
- `get` does not yet have a way to match based on value comparison `>=` or alike (TODO: dedicated issue, link here)

**Comment by aqw** [comment]
Same as #335

Many of the issues raised above have already been implemented or have their own issues.

The focus now is bringing those ideas to reality. Any future ones with have their own dedicated issue rather than continuing in this high-level discussion.
