### ISSUE TITLE
Rework dryrun approach

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#377]
Currently, quite a bunch of commands have a dryrun option and this is done by actually doing things and rolling-back afterwards. Apart from the superfluous staging of such to-be-rolled-back changes (see #370), most git commands actually do have a dryrun themselves, that would report what they would have done.
Utilize that!

**Comment by TobiasKadelka** [comment]
I think the existing #269 might already describe this problem that dry-run modifies temporarly and rolls changes back, instead of doing an actual dry-run.

FYI: This approach is used, because while sub-optimal, it at least prints a valid/real diff, while trying to create a diff manually on our own always led to problems in certain situations. But every other approach that replaces the current behavior is wished for - and just not found in an elegant efficient way yet :)

**Comment by bpoldrack** [comment]
@TobiasKadelka 
> For mv, rm and others with git-equivalent we already do that.

Depends on where. ;-)

So, `onyo mv` does use `git mv` w/ dryrun.
`onyo set`, however, also uses `git mv` but does actually call it on dryrun and then restore.

**Comment by bpoldrack** [comment]
> it at least prints a valid/real diff, while trying to create a diff manually on our own always led to problems in certain situations.

Not sure, what those issues were. Generally, I think it's worth exploring [difflib](https://docs.python.org/3/library/difflib.html) with the aim to only generate the to be written content in memory, diff-ing against current file content and only write after confirmation.
I have not used difflib but at a quick glance it looks like it should be a fit for us.
