### ISSUE TITLE
add `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#391]
We should add a `CONTRIBUTING.md` with the readme section "Code Conventions" to describe that the CLI tests should follow a normalized/standard sheme/order as a minimal requirement, and add some further information.

Here a short overview what I think should be mentioned:
  - call with single/simple path
  - call with multiple paths
  - call from different paths, e.g. subdirectories, etc
  - call with -C in different situations
  - explicit tests with and without all flags
  - explicit tests with combinations of flags
  - explicit tests for different error szanarios

**Comment by bpoldrack** [comment]
Hm. Not sure about this. For one thing: The conventional place to put such things would be a `CONTRIBUTING.md` rather than the `README`. Especially on GitHub the README is the entry point for everyone and it's a bit strange to me to see a whole bunch of things in there, that are only important to potential contributors.

Apart from this, the existing list of what to test, as well as the one you suggest here are a bit too strict in my view. They are insisting on making tests expensive and test everything over and over. For example: The `-C` flag is handled centrally. It doesn't matter what command one is calling. It's the exact same piece of code. What is gained by testing it with every single command call? What insight does the second time executing this code yield that the first time didn't?
Also: "Explicit tests" - I'd disagree with that as far as it refers to dedicated test functions. One can cover a couple of these scenarios in one test function. Difference being, that you'd run any setup for the test over and over for no good reason. If this is about being easily able to tell what failed when looking at the output of test runs, then I'd suggest to consider defining proper messages for assertions rather than relying on test names.
