### ISSUE TITLE
NITPICK: `onyo init` shows inconsistent output

### ISSUE THREAD

**Issue by nhjjr** [psyinfra/onyo#430]
When running `onyo init` two lines are shown as output:
```
Initialized empty Git repository in /path/to/dir/.git/
Initialized Onyo repository in /path/to/dir/.onyo/
```

The second (Onyo) line is missing 'empty'.

**Comment by TobiasKadelka** [comment]
The change in phrasing for consistency with git would normally make sense --- however, I feel in this case it would not necessarily be true adding "empty" to `Initialized Onyo repository in /path/to/dir/.onyo/`, because, we add example templates and an onyo config.

I do not want to argue much about this, but this was the motivation why I did not change the line so far.

**Comment by TobiasKadelka** [comment]
We will add the "empty", and change the git-information print to a debug message.
