### ISSUE TITLE
FEATURE: Allow asset key inheritance from asset-dirs

### ISSUE THREAD

**Issue by nhjjr** [psyinfra/onyo#432]
When creating an asset inside of an asset-dir it is useful to inherit certain key-values from the asset directory.

Example:
```
ASSETDIR=onyo new -k title="Arkham Horror: The Card Game (Revised Edition)" year=2021 designer="Nate French, Maxine Juniper Newman" players=1-4 time=60m
onyo mkdir $ASSETDIR
onyo new --inherit -k title="The Dunwich Legacy: Campaign Expansion" year=2022 cycle=1 type="campaign expansion" -p $ASSETDIR
```

This creates an asset directory of the boardgame "Arkham Horror: The Card Game". This game has quite a number of expansions by the same designers and the same number of players. By using `--inherit` the default values for these keys will be sourced from the asset-dir. Thus, 'The Dunwich Legacy' would have players=1-4, etc.

Note that some values, such as `faux`, should be non-inheritable. In that case, the template overrules the inheritance and creates a random value (instead of using the faux value).

**Comment by bpoldrack** [comment]
This idea needs to be fleshed out a little more. How to determine which key-value pairs ought to be inherited?
Just everything and override it by template? That would sort of imply that asset dir and its content can't use the same template (since it would overwrite everything).
Would it be good enough to make it explicit? IOW: Have `--inherit` get a list of keys that need to be explicitly specified?
If not, how to prevent particular keys from being inherited? You mentioned `serial`. But that doesn't generalize. There should be no hardcoded special behavior for that particular key name, IMO (Yes, I find the current approach for ''faux'' annoying in that regard - should be generalized. Just not highest priority for now)

**Comment by aqw** [comment]
This is an interesting idea, but I'm not sure where it is on that fine line between powerfully clever and too clever for its own good.

I personally would like to see the rest of onyo stabilize, and see how it functions in practice. Let this idea percolate a bit, and see how your use-case feels with the rest of the functionality in place, and how much this inheritance idea still helps (or obfuscates) functionality.

**Comment by aqw** [comment]
My understanding of this issue is that "inheritance" here means keys that are copied during asset creation rather than when queried. This use-case is flexibly met by the recently implemented `onyo new --clone`.

Closing. :-)

As an aside, the idea of keys that inherit values of parent directories (not just assets) dynamically at query-time (not simply copied at asset-creation) is an interesting and tantalizing idea, but one that I'm pretty sure it's closer to the negative outcome of Pandora's box. If someone is interested in that functionality, please open an issue outlining the use-cases that would support, syntax, and how validation of inherited values will work through renames, moving, changing, etc.
