### ISSUE TITLE
Find an alternative short-form for devices for `generate_commit_message()`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#475]
#462 points out that the flexible name schemes for assets mean that `paths = [x.name.split('_')[0] for x in path` do not necessarily lead to the `type` name field, this is just based on our current default implementation.

While not high priority, I wonder if there is not a reasonable replacement for this; e.g. selecting the first element of `onyo.assets.filename` which defines the filename for assets, and/or the biggest overlap in the name of all things the list of parameters given into `generate_commit_message()` or something like that.

I do not see a way that always works ATM, but somebody else might come up with a reasonable alternative :)

**Comment by aqw** [comment]
I recently rediscovered this issue, and this functionality is really from a different era of Onyo. Nowendays, no particular key has any more meaning than others. So specifying a particular key for the summarize to use when the subject is too long... it's pretty arbitrary and I don't think will work terribly well in practice.

If I make a change to many (let's say 42) assets, every single asset is listed in the subject. That does feel... intense.
```
set [42] (type): laptop_apple_mba2022... [42 assets are listed here]
```

I see a few options:
1) leave the behavior as is; it's not hurting anything
  - it's also not useful in any way; the Operations Summary is much more useful
2) naively decide what "too long" is and simply say "42 assets"
  - this feels pointless, as `set [42] (type)` already contains all that information
3) attempt some form of reduction of the asset name:
  - `set [42] (type): laptop_{apple,framework,lenovo,toshiba}_{16}_{42}`
  - short lists (some char length?) will list all fields, longer ones will say the number of variants
  - This doesn't feel all that much better. The primary improvement is that I can review how much variance there is.

If we can't design something that's clearly an improvement, then we should close this issue.

Thoughts?

**Comment by TobiasKadelka** [comment]
> If we can't design something that's clearly an improvement, then we should close this issue.

Lol, I just went to old issues with the goal to find at least one old issue that can be closed. Seeing your comment seems to justify my believe that this one is indeed out of date.

In praxis, I did experience this too (we have some very long commit messages), but it does not hurt, and there is still no better way this could be done. I will close here :)

**Comment by aqw** [comment]
I'm going to reopen this, because I would like to explore option 3 more before we abandon it.

**Comment by aqw** [comment]
My problem here is that the subject is filled with redundant information. It's all repeated in the body, and in a much better format for both humans and scripts.

My idea is that we consider that the keys in the asset name are human-relevant descriptors of the asset. I'm comfortable with that, as clearly the user has chosen them as a reasonable way to identify assets.

So running with that idea: we have a pile of assets that have been modified. Let's attempt to reduce that:

```
set [42]: type=laptop,desktop make={8} model.name={12} serial={42}
```

This, while imperfect, is indeed a summary of what happened. When we can list the key values, we do so. Otherwise, we count the number of unique values for that key.

Thoughts?

**Comment by aqw** [comment]
> The only thing I miss in your example is that we currently list also the keys which where changed, which I consider very important, even in the message.

Ahh, I missed that. Yeah, that information should be retained.

```
set [42] (type): type=laptop,desktop make=[8] model.name=[12] serial=[42]
```

>  i.e. if the number of different serials is actually needed, 

I don't think it's helpful to think about them as serials. Rather, imagine the keys as `a`, `b`, `c`, and `d`. They have no meaning. All we know is that the user has chosen these keys as good identifiers on the filesystem. That is the only reason why we are able to consider them relevant for the subject. Onyo knows they are important, but not what they mean (and that's ok).

**Comment by bpoldrack** [comment]
> `set [42] (type): type=laptop,desktop make=[8] model.name=[12] serial=[42]`

FTR: I don't think we'd want to make the logic **that** complicated. Either the values are listed for all keys or they are all collapsed to `[<number>]`. Figuring out which permutation of collapsing or not collapsing is short enough seems a bit cumbersome.

Other than that: Agreed.

**Comment by TobiasKadelka** [comment]
> I don't think it's helpful to think about them as serials. Rather, imagine the keys as `a`, `b`, `c`, and `d`. They have no meaning. All we know is that the user has chosen these keys as good identifiers on the filesystem. That is the only reason why we are able to consider them relevant for the subject. Onyo knows they are important, but not what they mean (and that's ok).

Yes of course, but even so there might be value in displaying `a`, it being the first field, for example, completely. Just numbers in the message subject will always mean less than displaying the first field more explicitly, so my thought. The big contra is that this would in some situations lead to too large subject lines once again. (I agree with Ben that trying to permutate over multiple/all possibilities is probably bad.)

So I would be already very happy to see the proposed shortening!

**Comment by aqw** [comment]
I agree that less complicated is a good thing. However, I think the implementation can be relatively easy to do the "right thing":

- build the full, expanded subject
- loop over it, if/while it's longer than `<configured length: default 75>`:
  - take the key with highest variability (or longest value string), and reduce the values into a number (e.g. `serial=[42]`)
  - continue until `< 75` or all values are reduced

> [...] there might be value in displaying `a`, it being the first field, for example, completely. [...]

I disagree. There is no way to know if `a` is any more relevant than `b`. For example, if I `set` something in all `apple` devices (second field in our inventory), that field is the most important, and not the `type` (the first, which might have half a dozen values).

**Comment by bpoldrack** [comment]
Fair. In any case: Can be figured in an implementation issue.

**Comment by aqw** [comment]
Damn. I thought we had this figured out, and then as I started writing the implementation issue, I realized that there's some open questions:

This behavior clearly applies to `set`, `unset`, and `new`. What's unclear to me is if it applies to other commands such as `mv`, `rm`, and `edit`. It clearly does not apply to `mkdir`.

My initial impulse is that we should use this idea wherever we can. The problem is the same: the commit message is unusable.

- `edit`: makes sense to use the approach in this issue
- `rm`: complicated because it can remove both directories and assets (IMO, this needs its own design issue; don't list children of a dir, etc)
- `mv`: complicated. moving or renaming a single asset/directory is covered by #708; multiple directories cannot be reduced; multiple assets... maybe should use the method in this issue. Perhaps this needs its own issue?

Thoughts?
