### ISSUE TITLE
BUG: `onyo new` allows multiple usages of `--path`, but does just use the last one

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#539]
When I want to create 2 devices with two different "make" (and everything else being equal), I would type e.g. `--keys make=lenovo make=apple`.
When I try to add 2 different directories for these, onyo allows that I do `--path a/ --path b/` (no error raised), but it just applies the second directory to all newly created assets:

```
> onyo new --keys RAM=8GB display=14.6 type=laptop make=lenovo make=apple model=T490s serial=faux --path shelf/ --path a/
The following will be created:
--- 
+++ /Users/tkadelka/onyo/a/laptop-lenovo-T490s.fauxC7MBPj
@@ -1 +1,6 @@
-{}
+RAM: 8GB
+display: 14.6
+type: laptop
+make: lenovo
+model: T490s
+serial: fauxC7MBPj
--- 
+++ /Users/tkadelka/onyo/a/laptop-lenovo-T490s.fauxfYv0KX
@@ -1 +1,6 @@
-{}
+RAM: 8GB
+display: 14.6
+type: laptop
+make: apple
+model: T490s
+serial: fauxfYv0KX
Create assets? (y/n) 
```

**Comment by TobiasKadelka** [comment]
Further testing shows, that actually this is true for specifying `--keys` two times, too:
```
> onyo new --keys RAM=8GB display=14.6 type=laptop make=lenovo model=T490s serial=faux --keys make=apple type=laptop model=T490s serial=faux --path shelf/
The following will be created:
--- 
+++ /Users/tkadelka/onyo/shelf/laptop-apple-T490s.fauxkOEtK8
@@ -1 +1,4 @@
-{}
+make: apple
+type: laptop
+model: T490s
+serial: fauxkOEtK8
Create assets? (y/n) 
```

IMO we should check if this is true for all commands/arguments, and if possible block the double-usage of flags that overwrite each other, and instead raise an error, explaining the contradiction.

**Comment by aqw** [comment]
This seems to be a known limitation of `argparse`.

- https://stackoverflow.com/questions/14915986/only-one-command-line-argument-with-argparse
- https://stackoverflow.com/questions/23032514/argparse-disable-same-argument-occurrences

Using a custom action looks to be the most appropriate way. The onyl problem is that it will "conflict" with some of the existing actions. These are the ones in use:

- `store_true` (8)
- `store_false` (1)
 - `version` (1)
- `append` (1)
- `StoreKeyValuePairs` (2)

`store_true`, `store_false`, and `version` won't create any problems if they are specified multiple times. So that's easy. `append` intentionally wants that behavior. So that leaves `StoreKeyValuePairs`, which will need to be extended to include the behavior of the new custom action.

**Comment by bpoldrack** [comment]
Note, that WRT to `--path` it simply shouldn't be allowed multiple times any more (I see an argument for this for `--keys`, though).
If multiple assets need to be created in different dirs, the `directory` reserved key is the way to go - either via `--keys` or TSV.

**Comment by TobiasKadelka** [comment]
> If multiple assets need to be created in different dirs, the directory reserved key is the way to go

Good point, this should be described in read the docs!

**Comment by aqw** [comment]
> If multiple assets need to be created in different dirs, the directory reserved key is the way to go - either via --keys or TSV.

This will require some sort of `append` functionality.

**Comment by TobiasKadelka** [comment]
I understood that this will not require anything , since it is already implemented.

And indeed, when I run `onyo new --keys directory=shelf directory=advertisement [all other stuff needed]` it works like a charm :)

So only the behavior for using the same flag multiple times (caused by arg-parse) needs to be fixed, and I will add a PR for readthedocs adding the explanation for multiple `directory` tomorrow.
