### ISSUE TITLE
DOCs: explain how to `onyo cat` all assets in a(n asset) directory

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#566]
With #557  `onyo cat <asset-dir>` on the directory will cat the contents of the file `<asset-dir>/.onyo-asset-dir`.
To `onyo cat` all assets in an asset directory (or any other type of directory, for that matter) one must use `onyo cat asset-dir asset-dir/*`.

This way to cat the contents of an asset directory that are not already in the `.onyo-asset-dir` file needs to be added to the help text and readthedocs.

**Comment by bpoldrack** [comment]
Why do we need to explain basic shell functionality in our docs?
`onyo cat` takes a list. Imo that's all one needs to know.

**Comment by aqw** [comment]
What's the name of the file for the "root" (for lack of a better term) asset? If it starts with `.`, then shell globbing won't work by default.

**Comment by TobiasKadelka** [comment]
This is not about shell as such. It is about explicitely and specifically stating that `onyo cat <asset-dir>` does not "print everything inside an asset dir", it shows just the contents of `.onyo-asset-dir`, even though the assets inside an asset dir (e.g. a part exchanged in the "cluster asset directory" that is also its own asset) are part of the asset-dir.

I found the comment to document this in the chat valid, because onyo is not about files/directories on a fundamental level, but about assets and the information about them. So I think the explanation what `onyo cat <asset-dir>` prints and what not is important for me (or rather new users) to understand how onyo is designed.

**Comment by TobiasKadelka** [comment]
Which makes me now think: does `onyo get --path <asset-dir>` query by default recursively all files beneath the asset directory, or just the `.onyo-asset-dir`? Does the behavior align with the information one gets for `onyo cat <asset-dir>` (e.g. do they select the same files)?

This is not 100% obvious to me and needs to be documented, too.

**Comment by bpoldrack** [comment]
@TobiasKadelka 
Hm. I think the confusion comes from a somewhat outdated idea of asset dirs (so doesn't apply to new users). You keep thinking about it as a special entity. It's not. It is an asset. Period.

`onyo cat` takes a list of assets to print. Whether `some/asset` is or isn't also a dir is completely irrelevant. Why would anyone think, that it prints all assets within? You point it to the asset(s) to print. There's nothing different about an asset dir. That would only be relevant if `cat` did this for any directory. Which it doesn't.

> onyo get --path <asset-dir>
> [...]
> onyo cat <asset-dir> (e.g. do they select the same files)?

You do not select the same files in these two cases. Because `cat` does not take directories.
So, yes - `get` should query all the assets. Because it does consider dirs and it is a dir.


@aqw 
> What's the name of the file for the "root" (for lack of a better term) asset? If it starts with ., then shell globbing won't work by default.

It does. But onyo knows that the asset dir is itself an asset. Hence:
`onyo cat <asset-dir>` gives that one asset,
`onyo cat <asset-dir>/*` gives all assets within, and
`onyo cat <asset-dir> <asset-dir>/*` gives the container asset itself and all within.

**Comment by bpoldrack** [comment]
IMO there's nothing to do, hence closing.
