### ISSUE TITLE
implement anchoring-by-default

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#58]
This is the successor to #31

- [x] `onyo ls` should not list `.anchor` files
- [x] `onyo tree` should not show `.anchor` files
- [x] `onyo new` should not create folders by default (see #57)
- [x] `onyo mv` should not create folders by default (see #57)

**Comment by TobiasKadelka** [comment]
`onyo mv` and `onyo new` will stop creating folders in an incomming PR, that also removes `onyo anchor` and `onyo unanchor`.

`onyo ls` is not yet implemented.
I made a comment in #54 so it is remembered when it will be implemented, so after the above mentioned PR I will close this issue, since all tasks are either done or the information put in a more specific issue.

**Comment by TobiasKadelka** [comment]
This is done and the PR merged, so I close this.
