### ISSUE TITLE
design `onyo history`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#6]
Print the history of an asset.

I am debating whether this should simply spawn `tig`, or if it should be a prettified output of `git log` that should the commit messages (which should be human readable/sane) and diffs (if any).

**Comment by TobiasKadelka** [comment]
I looked a bit into the different options and am thinking this:
`onyo history <path to folder or file>` should do `tig --follow <path to folder or file>`.

Additionally (thougths are wished), `git --no-pager log <path to folder or file>` might be used when a `onyo history --non-interactive <path to folder or file>` is called, so that non-interactive history can be e.g. printed in a file, instead of opening. My thoughts behind using these two different things are, that I prefer `tig` with its output and menu, but that for coding onyo the `git log` would be still possible to use and nice to have.

**Comment by TobiasKadelka** [comment]
Update:
`git --no-pager log --follow` is used so the output with and without --non-interactive is the same, I forgot to add that in the comment above.

If no path is given, the onyo root directory is used and the whole history of that repository is shown.

**Comment by aqw** [comment]
I agree that having both interactive and non-interactive are a good idea. The commands look sane to me.

It would be best if the commands can be overriden by a user configuration option, to allow the flexibility to use alternate outputs.

**Comment by aqw** [comment]
One more thing: I assume Onyo will detect if its running in an interactive TTY or not, and then choose interactive/non-interactive based on that.

Do you have plans to allow the user to force the mode via `--interactive` and `--non-interactive` flags (or something similar)?

**Comment by TobiasKadelka** [comment]
The plan is to have that flag to allow both modes when used by TTY, whatever the user prefers.
If not TTY, it is automatically non-interactive and just the log is printed, without tig.
