### ISSUE TITLE
`new`: Shell completion for `--template`

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#625]
With PR #624 that switch has changed and allows for absolute and relative paths instead of names. Shell completion should seek to complete relative to the template dir as well as CWD.

**Comment by aqw** [comment]
Hmm. While I'm ok with an explicit path to the template being provided (rather than just relative to the template dir), I think we should not support this in tab completion.

It's pretty complicated to implement, but moreso, I think it will be confusing to the user.

I'm struggling to think of a tab completion I've used that silently switches between lists/target directories to complete for. I have seen such switches when a protocol is used (I can't remember which command though). The default is to the local FS, but once `ssh://` is specified it starts looking through a different path. That feels intuitive, because the user is explicit in their declaration for a protocol.

The proposed behavior here is that a user will hit tab, get a list from template dir. Then if they type a character sequence that does not exist in the template dir, then we will switch to complete off of CWD. Silently. That feels very non-obvious. And will also break substring behavior. For example, if I type `onyo new --template apple<TAB>`, my ZSH will filter the list for all templates that include the string "apple" (because none of them /start/ with "apple").

In the end, I don't see an intuitive, clean way to support this.

I'm closing, but I am very open to discussing this if someone feels that I'm missing something. So please feel free to reopen and engage. :-)
