### ISSUE TITLE
`--message` should append to rather than overwrite the commit message

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#685]
In practice, we have found that it is far, far more common to want to *add* a note to the commit message than it is to overwrite the informative, auto-generated commit message. For example:

```
onyo mv shelf/laptop_apple_mba2023.abc1234 Bingo\ Bob/ --message "close #1127"
```

I propose the following:
- `-m, --message MESSAGE`: Append the given MESSAGE to the auto-generated commit message. If multiple `--message` options are given, their values are concatenated as separate paragraphs.
- `-M, --message-overwrite MESSAGE`: Use the given MESSAGE as the commit message (discarding the default). If multiple `--message` options are given, their values are concatenated as separate paragraphs.

In a conversation with Ben, I had a better idea than `--message-overwrite`, but I have since forgotten in. Grr.

What is unclear to me is whether `-m` and `-M` can be used together. I feel like they should not. But, they both fundamentally have the same append behavior.

Alternate idea that avoids the behavioral ambiguity above:

- `--discard-auto-generated-commit-message`: Discard the auto-generated commit message. Requires `-m, --message`.
- `-m, --message MESSAGE`: Append the given MESSAGE to the commit message. If multiple `--message` options are given, their values are concatenated as separate paragraphs. To discard the auto-generated commit message, see `--discard-auto-generated-commit-message`.
- `-M, --message-overwrite`: short for `--message` and `--discard-auto-generated-commit-message`

I don't like the verbosity of `--discard-auto-generated-commit-message`, but at least it's clear. ;-) Better ideas are most welcome.

Open questions:
- will overwriting (discarding, whatever) retain or remove the inventory operations log? In other words: are we overwriting the subject line or indeed the entire message? Do we want each to be controllable? Like `--no-autogen-msg=subject,operations`.

**Comment by aqw** [comment]
I currently favor the "alternate idea".

**Comment by TobiasKadelka** [comment]
I fully agree on the "don't overwrite the auto generated message". I liked them from the beginning, and since we are using onyo in practice I find them even more helpful than I thought they would be.

If you are looking for alternative names to `--discard-auto-generated-commit-message`, I think `--no-auto-message`  or `--no-auto-header` are sufficient. The flag will mainly be discovered through help/docs, so as long as the explenation there is explicite enough these shorter flag names will do the job.
(but truth be told, either I use the `--discard-auto-generated-commit-message` flag rarely, then I do not care if it has a longer name, or I use it all the time, then I use my terminal history. Either way I have tab completion.)

I am against removal of the "inventory operations log", I think it should always be there at the end.

**Comment by nhjjr** [comment]
I agree that appending to a message is very useful, but doing so by default for `--message` isn't really implied, especially if you're familiar with git. 

I would suggest `--message-method` (or mode, or whatever you want to call it) that has two or three options:
1. 'overwrite' (default): overwrites the entire message with the new message but keep the operations log
2. 'append': appends the message behind the onyo line
3. 'no-log': overwrite but remove the operations log
4. 'aqw': alex' brilliant idea once he remembers it

One could set this in an onyo config file so that the default `--message-method` can be different without having to be verbose about it.

**Comment by TobiasKadelka** [comment]
I do not like the `--message-method` flag idea. It will make most calls more complicated than necessary, one has to remember another flag and its options, and in the end I see no real usecase when I would want to have all these different options.

The more I think about it, and all the times I used onyo the last few months, the more I think the change that onyo really needs is literally just what the issue title already states: append the message body, instead of overwriting the header. I *might* see the usage for a true/false flag which allows overwriting the header too, but having a more complicated flag "just in case" does not improve anything for me.

(I want to say: I apprechiate the idea even though I argue against it; it does help me greatly with re-considering how I want to use onyo and its flags, and when I want maximum flexibility, and when I just want it to be simple! :)

**Comment by nhjjr** [comment]
To clarify, my idea of `--message-method` has its default in how `--message` currently works. That is, to maintain current functionality a user would not have to provide an argument for `--message-method`. If the preferred common approach is to append, then a user could set this in their config file and likewise no longer has to use `--message-method`. Its use is only for non-standard cases.

Giving it some more thought, the commit message is written through an onyo command, so one can expect the command to behave differently from a git commit. A default `--message` that appends may be better, and the question then is whether we even need one that overwrites (at the cost of adding more arguments and making at least the help text bigger).

**Comment by aqw** [comment]
Hmmm, your `--message-method` got be thinking... what if we expose controlling what is auto-generated.

- `--autogenerated-commit-message` (better name needed, clearly)

And there are two values:
- `subject`
- `operations`

The default would be `subject,operations`. To enable "full overwrite" mode, one would pass `--autogenerated-commit-message=""`. If one wanted to keep one or the other, they could also specify that.

**Comment by nhjjr** [comment]
I like the `--autogenerated-commit-message` idea. You'll leave it alone for standard use and never think about it, and either use it as an argument or add it to an inventory's config file for non-standard use. 

I don't even think the name is bad, because lengthy names imply it's not a feature that should be used regularly (e.g., prefer a standardized approach via .onyo config) and it's pretty explicit in its functionality.

**Comment by bpoldrack** [comment]
Ok, so here is my conclusion:

1. Make appending the default (as in: the autogenerated part remains)
2. Have an option to discard the autogenerated part and possibly (I think: most certainly) a config to default to that.
3. Operations log: No, there won't be an option to discard that (or to append anything after it). Whoever finds a `git commit --amend` to complicated to do that, doesn't know what he's doing. Period.

That leaves us with the question of how to name that option for 2.
I'm currently in favor of `--no-auto-message`.

**Comment by aqw** [comment]
I like your summary. And I am comfortable with `--no-auto-message`. :-)

**Comment by nhjjr** [comment]
+1 for me on Ben's reply with but two remakrs:
- What happens if the subject line is not auto-generated (e.g., via config) but no custom message is given? Error?
- `--no-auto-message` implies it's a boolean, but it's a str (list) of `"subject,operations"`. I'd suggest `--autogen-message` or some such.

**Comment by aqw** [comment]
> What happens if the subject line is not auto-generated (e.g., via config) but no custom message is given? Error?

IMO: No error. Just empty subject.

> `--no-auto-message` implies it's a boolean, but it's a str (list) of `"subject,operations"`.

Ben proposes that the Inventory Operations is not optional. It shall always be added. Thus the flag would only control the subject, and be a toggle.

**Comment by nhjjr** [comment]
> Ben proposes that the Inventory Operations is not optional. It shall always be added. Thus the flag would only control the subject, and be a toggle.

In that case I have no problem with `--no-auto-message`, and an empty subject line works for me too. Turns out I'm all in favor of Ben's proposal!

**Comment by bpoldrack** [comment]
> What happens if the subject line is not auto-generated (e.g., via config) but no custom message is given? Error?

`git commit` comes with `--allow-empty` but would error by default. We should do the same. I guess we'll just try and relay git's error. That's because there may a way to configure `allow-empty` for git (now or in the future). Implication: We add `--allow-empty` and pass it on. Default False.

> --no-auto-message implies it's a boolean, but it's a str (list) of "subject,operations". I'd suggest --autogen-message or some such.

Not sure I parse that. It does imply it's boolean. Yes. It's not a string. Because not generating the operations log is not an option.

**Comment by bpoldrack** [comment]
FTR: Turns out I haven't seen the posts after the one I quoted ;-)

**Comment by nhjjr** [comment]
> Not sure I parse that. It does imply it's boolean. Yes. It's not a string. Because not generating the operations log is not an option.

Disrgard my comment here. I misinterpreted the bit about the operations log not being optional. 

I'm in favor of mirroring git's approach over allowing empty commit messages by default.

**Comment by bpoldrack** [comment]
Hold on. @aqw is right. We allow empty. That's because it's not actually empty. We always at the operations record.

**Comment by nhjjr** [comment]
> Hold on. @aqw is right. We allow empty. That's because it's not actually empty. We always add the operations record.

Wouldn't that turn the operations log, normally in the message body, into the message subject? If we don't necessarily differentiate between subject and body that's fine, but if we do it may be problematic.

**Comment by bpoldrack** [comment]
@nhjjr 

> Wouldn't that turn the operations log, normally in the message body, into the message subject? If we don't necessarily differentiate between subject and body that's fine, but if we do it may be problematic.

Not sure from the top of my head, but I'll solve that - no worries. This is not a conceptual issue.
