### ISSUE TITLE
design `onyo fsck`

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#7]
Onyo should strive to always keep the repo in a sane state. However, the user can always do stuff manually, and bugs are possible. Also, as a completely legitimate use-case, a user may update a validation template, and want `onyo` to perform a sanity check to flag all assets which don't comply with this change.

In general, `onyo fsck` should be as comprehensive as it can.
- validate all file names
- validate that all asset names are unique
- check that all files are valid YAML
- validate the contents of all files against their respective templates
- ensure there are no untracked files in the git repo (unless ignored by `.gitignore`)
- ensure that all dirs have a `.anchor` file

**Comment by aqw** [comment]
Added `.anchor` file check.

**Comment by TobiasKadelka** [comment]
Since I am currently working on this, I will briefly summarize, what I am doing and planning. This contains not all checks from the list above, but instead all the things which are missing or unclear, since `onyo fsck` is not yet documented. All points are open for discussion and feedback is wished for!

`onyo fsck` has no arguments (so far). It uses either `$ONYO_REPOSITORY_DIR` or the current working directory (decided by onyo main.py).

Assuming a onyo repository `onyo_dir/` containing a folder `shelf/`, it checks if `onyo_dir/` is a valid git repository, and if not, errors out and does no further checks. Being in a subfolder like `shelf/` is ok, but `onyo_dir/` is completely checked.

If the git-repository is valid, it does all of the following checks (and prints the errors out, after *all* checks are done):
1. checks for untracked files or uncommited changes (basically, "is git working tree completely clean?"), respecting `.gitignore`.
In your list of checks above, it just mentions untracked files. I would think the repo should be completely clean, or otherwise something went already wrong, so we should discuss this.
2. Checks if the git repository has a folder `.onyo/` (on the same level as `.git/`).
This is not mentioned above, but I think should be mandatory, especially to differentiate between being in an onyo repository, or just in a normal git. Maybe this should even happen before the other checks and error out without further checks, since `onyo fsck` now could be run on a normal git folder and would throw for all folders errors about missing anchors, for all files errors that they are no real yaml assets, etc.
3. Do all folder have a `.anchor` file? Excluded from this check are `.git/` and folders mentioned in `.gitignore`. This makes it possible, to have in an onyo repository other files, folders, subfolders, that do not have to be tracked with onyo, without throwing errors.

**Comment by TobiasKadelka** [comment]
Possibly it will help to provide example output. I build a normal/correct onyo repository and created there manually folders and files (with touch and mkdir) that are not onyofied, and wrote into one of the assets invalid yaml syntax.

```
(onyo) tkadelka@bnbmac in ~/new-onyo/onyo_tests/test_1 on git:master
❱ onyo fsck              
onyo repo: /Users/tkadelka/new-onyo/onyo_tests/test_1
ERROR:onyo:

The Onyo working tree is not clean.

Untracked files: 
	 trash bin/unadded_file
Please commit all changes or add new files to .gitignore

.anchor is missing:
	shelf/new_folder_without/.anchor
	shelf/new_folder_without/another_folder/.anchor

Some yaml files have incorrect syntax:
	user/laptop_apple_macbookpro.5

```

**Comment by TobiasKadelka** [comment]
Above, I updated the example output with an example reaction about double asset names.

In general, even if not explicitely mentioned in the first post of this issue, I think the `.gitignore` should be respected by *all* checks done. Folders/Assets/Files that are gitignored should be excluded from the yaml check and uniqueness etc.

**Comment by TobiasKadelka** [comment]
Still missing, and put off for now (since discussion about templates and naming schemes are required):
- validate all file names
- validate the contents of all files against their respective templates

**Comment by TobiasKadelka** [comment]
To summarize the conclusion from the meeting:
General direction of output is good. The user should be informed about how to fix the problem and/or what caused it, so additional output will be added in a future PR.
