### ISSUE TITLE
onyo -C </path/to/run/> <command>

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#81]
We discussed multiple times, if we want to have a -C flag.
The implementation would be fairly straight forward, so I want to first discuss the behaviour and consequences of this. In general: It would enable to run an onyo command in an onyo repository B, while being in repository A.

1. Should this overwrite `$ONYO_REPOSITORY_DIR`, or throw an error if the var is set and -C is used?
2. How should this behave (assuming `$ONYO_REPOSITORY_DIR` is unset) :
`onyo -C /path/a/ git -C /path/b/ status`
I would argue, it should basically run as if double-redirected and show`git status` for /path/b/

**Comment by aqw** [comment]
>  In general: It would enable to run an onyo command in an onyo repository B, while being in repository A.

I disagree with this characterization. It allows one to run `onyo` on an onyo repository from anywhere on the filesystem (not just inside of another onyo repo).

I looked at the git manpage to see what they do (why invent when you can copy ;-), and I do not see an environment variable for the repository. I think that is controlled only by `-C`.

`pass` seems to be the opposite. With only the environment variable and no `-C`.

I am conflicted, and need to think on this a bit. Having both increases the chance of a conflict. `-C` feels more explicit, so I prefer that. The environmental variable is a shade easier for those who want to use just one onyo repo, and not care where they are on the system.

I'm open to all thoughts / suggestions.

> Should this overwrite $ONYO_REPOSITORY_DIR, or throw an error if the var is set and -C is used?

I think we should throw an error, otherwise we're guessing. Which is bad.

> How should this behave (assuming $ONYO_REPOSITORY_DIR is unset) : `onyo -C /path/a/ git -C /path/b/ status`

That is a good point, and I think that problem exists even without `ONYO_REPOSITORY_DIR` or `onyo -C`. I think this is a separate design bug (and I think we should protect against).
